{% set name = "napari-boardgame-maker" %}
{% set version = "0.0.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/napari-boardgame-maker-{{ version }}.tar.gz
  sha256: cb05a9254705ac752a73a5f247dbfc92d7817415ac6b9609ded1e781b5f03bf9

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools >=42.0.0
    - wheel
  run:
    - imagecodecs
    - magicgui
    - matplotlib-base  # Not declared, but used
    - napari
    - napari-stl-exporter
    - napari-tools-menu
    - numpy
    - python >=3.8
    - qtpy
    - scikit-image  # Not declared, but used
    - scipy  # Not declared, but used
    - vedo

test:
  imports:
    - napari_boardgame_maker
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/napari-boardgame-maker
  summary: Make boardgame tiles
  description: |
    This plugin turns 2D grayscale images into 3D-printable landscape tiles
    for a certain all-time tabletop boardgame which revolves around building
    settlements, obtaining ressources expanding and collecting more points
    than your opponents.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
